[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "docker build -t pms-frontend ."

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
REACT_APP_API_URL = "${{BACKEND_URL}}/api"
PORT = "3000"