# Generated by Django 5.2.5 on 2025-08-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.worksite'),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
