# Generated by Django 5.2.5 on 2025-08-24 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('quote', 'Quotation'), ('purchase_order', 'Purchase Order'), ('dispatch_note', 'Dispatch Note'), ('receipt', 'Delivery Receipt'), ('invoice', 'Invoice'), ('other', 'Other Supporting Document')], help_text='Type of procurement document', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('object_name', models.CharField(help_text='MinIO object name/path', max_length=500, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('failed', 'Upload Failed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Document description or notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (vendor info, PO number, etc.)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requisition.request')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'document_type'], name='procurement_request_df944d_idx'), models.Index(fields=['object_name'], name='procurement_object__5c5076_idx')],
            },
        ),
    ]
