# Generated by Django 5.2.6 on 2025-09-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_procurementdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='current_approver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='final_approver',
        ),
        migrations.AddField(
            model_name='request',
            name='approval_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='last_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_last_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
