# Generated by Django 5.2.7 on 2025-10-09 19:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0004_add_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateTimeField(help_text='Start of the archived period')),
                ('period_end', models.DateTimeField(help_text='End of the archived period')),
                ('file_path', models.CharField(help_text='Path to ZIP file on disk', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='ZIP file size in bytes')),
                ('request_count', models.IntegerField(help_text='Number of requests archived')),
                ('archived_request_ids', models.JSONField(default=list, help_text='List of archived request IDs')),
                ('archived_request_numbers', models.JSONField(default=list, help_text='List of archived request numbers')),
                ('downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-archive_date'],
                'indexes': [models.Index(fields=['downloaded', 'archive_date'], name='requisition_downloa_f7bcdc_idx')],
            },
        ),
    ]
