name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH

    - name: Deploy Backend to Railway
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: |
        cd pms-be
        railway link --project ${{ secrets.RAILWAY_BACKEND_PROJECT_ID }}
        railway up --detach

    - name: Deploy Frontend to Railway
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: |
        cd pms-fe
        railway link --project ${{ secrets.RAILWAY_FRONTEND_PROJECT_ID }}
        railway up --detach

    - name: Wait for deployments
      run: |
        echo "Backend and frontend deployments initiated successfully"
        echo "Check Railway dashboard for deployment status"